name: "Setup CMake on Windows"
description: "Downloads a specific CMake version and adds it to PATH on Windows runners. Does not require admin rights."
inputs:
  version:
    description: "CMake version (e.g. 3.29.9)"
    required: false
    default: "3.29.9"
runs:
  using: "composite"
  steps:
    - name: "Check for existing CMake"
      id: check
      shell: powershell
      run: |
        if (Get-Command cmake -ErrorAction SilentlyContinue) {
          Write-Host "cmake already installed"
          "installed=true" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
        } else {
          "installed=false" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
        }

    - name: Cachetest
      uses: tespkg/actions-cache@v1
      with:
        endpoint: ${{ secrets.S3_NB_CACHE_HOST }}
        accessKey: ${{ secrets.S3_NB_CACHE_ACCESS_KEY }}
        secretKey: ${{ secrets.S3_NB_CACHE_SECRET_KEY }}
        bucket: ${{ secrets.S3_NB_CACHE_BUCKET }}
        use-fallback: true
        path: |
          $env:RUNNER_TEMP\cmake
        key: ${{ runner.os }}-cachetest-${{ github.ref_name }}-${{ hashFiles('package-lock.json', '**/package-lock.json', 'src-tauri/Cargo.lock', '**/Cargo.lock') }}-${{ github.run_id }}
        restore-keys: |
          ${{ runner.os }}-cachetest-${{ github.ref_name }}-${{ hashFiles('package-lock.json', '**/package-lock.json', 'src-tauri/Cargo.lock', '**/Cargo.lock') }}-
          ${{ runner.os }}-cachetest-${{ github.ref_name }}-
          ${{ runner.os }}-cachetest-

    - name: Install CMake dependency (Windows)
      if: steps.check.outputs.installed != 'true'
      shell: powershell
      env:
        CMAKE_VERSION: ${{ inputs.version }}
      run: |
        $v = $env:CMAKE_VERSION
        [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
        $url = "https://github.com/Kitware/CMake/releases/download/v$v/cmake-$v-windows-x86_64.zip"
        $zip = "$env:RUNNER_TEMP\cmake-$v.zip"
        $destRoot = "$env:RUNNER_TEMP\cmake"

        if (Test-Path $destRoot) { Remove-Item $destRoot -Recurse -Force }
        New-Item -ItemType Directory -Path $destRoot | Out-Null

        Invoke-WebRequest $url -OutFile $zip
        Expand-Archive -LiteralPath $zip -DestinationPath $destRoot -Force

        $extractDir = Get-ChildItem $destRoot -Directory | Select-Object -First 1
        $bin = Join-Path $extractDir.FullName 'bin'
        $bin | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - name: Show CMake version (Windows)
      shell: powershell
      run: cmake --version
