name: "Setup sccache"
description: "Installs sccache for caching Rust builds"
inputs:
  version:
    description: "Sccache version"
    required: false
    default: "0.12.0"
  s3_host:
    description: S3 endpoint for cache
    required: false
  s3_access_key:
    description: S3 access key for cache
    required: false
  s3_secret_key:
    description: S3 secret key for cache
    required: false
  s3_bucket:
    description: S3 bucket for cache
    required: false

runs:
  using: "composite"
  steps:
    - name: "Check for existing sccache"
      id: check
      shell: powershell
      run: |
        if (Get-Command sccache -ErrorAction SilentlyContinue) {
          Write-Host "sccache already installed"
          "installed=true" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
        } else {
          "installed=false" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
        } 

    - name: "Install sccache"
      if: steps.check.outputs.installed != 'true'
      env:
        SCCACHE_VERSION: ${{ inputs.version }}
      shell: powershell
      run: |
        $ErrorActionPreference = "Stop"

        $v = $env:SCCACHE_VERSION
        $url = "https://github.com/mozilla/sccache/releases/download/v$v/sccache-v$v-x86_64-pc-windows-msvc.zip"
        $zip = "$env:RUNNER_TEMP\sccache-$v.zip"
        $destRoot = "$env:RUNNER_TEMP\sccache"

        if (Test-Path $destRoot) { Remove-Item $destRoot -Recurse -Force }
        New-Item -ItemType Directory -Path $destRoot | Out-Null

        Invoke-WebRequest $url -OutFile $zip
        Expand-Archive -LiteralPath $zip -DestinationPath $destRoot -Force

        # Find sccache.exe regardless of archive layout
        $sccacheExe = Get-ChildItem -Path $destRoot -Recurse -Filter "sccache.exe" | Select-Object -First 1
        if (-not $sccacheExe) {
          Write-Host "Could not find sccache.exe under: $destRoot"
          Get-ChildItem -Path $destRoot -Recurse | Select-Object FullName | Format-Table -AutoSize
          throw "sccache.exe not found after extracting archive"
        }

        # Copy into a short, stable dir to avoid Windows long-path issues
        $binDir = "$env:RUNNER_TEMP\bin\sccache"
        if (Test-Path $binDir) { Remove-Item $binDir -Recurse -Force }
        New-Item -ItemType Directory -Path $binDir | Out-Null

        $binExe = Join-Path $binDir 'sccache.exe'
        Copy-Item -LiteralPath $sccacheExe.FullName -Destination $binExe -Force

        # IMPORTANT: write to GITHUB_PATH, not env:Path.
        # GITHUB_PATH affects subsequent steps, not necessarily the current step.
        $binDir | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

        # Verify in the same step using absolute path (so we don't depend on PATH update timing)
        & $binExe --version

    - name: "Enable sccache + GitHub Actions cache backend"
      shell: powershell
      env:
        SCCACHE_BUCKET: ${{ inputs.s3_bucket }}
        SCCACHE_ENDPOINT: ${{ inputs.s3_host }}
        SCCACHE_ACCESS_KEY_ID: ${{ inputs.s3_access_key }}
        SCCACHE_SECRET_ACCESS_KEY: ${{ inputs.s3_secret_key }}
      run: |
        # Rust: use sccache as compiler wrapper
        Add-Content -Path $env:GITHUB_ENV -Value "RUSTC_WRAPPER=sccache"

        # Optional but commonly recommended for CI: incremental builds aren't cacheable by sccache
        # (release builds usually have this off already, but this makes it explicit)
        Add-Content -Path $env:GITHUB_ENV -Value "CARGO_INCREMENTAL=0"

        # Enable GitHub Actions cache backend for sccache
        Add-Content -Path $env:GITHUB_ENV -Value "SCCACHE_GHA_ENABLED=true"
        Add-Content -Path $env:GITHUB_ENV -Value "SCCACHE_CACHE_SIZE=5G"
        Add-Content -Path $env:GITHUB_ENV -Value "SCCACHE_BUCKET=$env:SCCACHE_BUCKET"
        Add-content -Path $env:GITHUB_ENV -Value "SCCACHE_ENDPOINT=$env:SCCACHE_ENDPOINT"
        Add-Content -Path $env:GITHUB_ENV -Value "SCCACHE_REGION=auto"
        Add-Content -Path $env:GITHUB_ENV -Value "AWS_ACCESS_KEY_ID=$env:SCCACHE_ACCESS_KEY_ID"
        Add-Content -Path $env:GITHUB_ENV -Value "AWS_SECRET_ACCESS_KEY=$env:SCCACHE_SECRET_ACCESS_KEY"

    - name: "Export required runtime variables for sccache (GHA backend)"
      if: ${{ runner.os == 'Windows' }}
      uses: actions/github-script@v7
      with:
        script: |
          core.exportVariable('ACTIONS_RESULTS_URL', process.env.ACTIONS_RESULTS_URL || '');
          core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

    - name: "Start sccache server + show initial stats"
      shell: powershell
      run: |
        $ErrorActionPreference = "Stop"
        if (-not (Get-Command sccache -ErrorAction SilentlyContinue)) {
          Write-Host "sccache is not on PATH. PATH is:"
          Write-Host $env:PATH
          throw "sccache not found on PATH"
        }
        sccache --start-server
        sccache --show-stats
