name: "Setup sccache"
description: "Installs sccache for caching Rust builds"
inputs:
  version:
    description: "Sccache version"
    required: false
    default: "0.12.0"
  s3-host:
    description: "S3 endpoint for sccache (e.g. https://s3.example.com)"
    required: false
  s3-access-key:
    description: "S3 access key for sccache"
    required: false
  s3-secret-key:
    description: "S3 secret key for sccache"
    required: false
  s3-bucket:
    description: "S3 bucket for sccache"
    required: false

runs:
  using: "composite"
  steps:
    - name: "Check for existing sccache"
      id: check
      shell: powershell
      run: |
        if (Get-Command sccache -ErrorAction SilentlyContinue) {
          Write-Host "sccache already installed"
          "installed=true" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
        } else {
          "installed=false" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
        } 

    - name: "Install sccache"
      if: steps.check.outputs.installed != 'true'
      env:
        SCCACHE_VERSION: ${{ inputs.version }}
      shell: powershell
      run: |
        $ErrorActionPreference = "Stop"

        $v = $env:SCCACHE_VERSION
        $url = "https://github.com/mozilla/sccache/releases/download/v$v/sccache-v$v-x86_64-pc-windows-msvc.zip"
        $zip = "$env:RUNNER_TEMP\sccache-$v.zip"
        $destRoot = "$env:RUNNER_TEMP\sccache"

        if (Test-Path $destRoot) { Remove-Item $destRoot -Recurse -Force }
        New-Item -ItemType Directory -Path $destRoot | Out-Null

        Invoke-WebRequest $url -OutFile $zip
        Expand-Archive -LiteralPath $zip -DestinationPath $destRoot -Force

        # Find sccache.exe regardless of archive layout
        $sccacheExe = Get-ChildItem -Path $destRoot -Recurse -Filter "sccache.exe" | Select-Object -First 1
        if (-not $sccacheExe) {
          Write-Host "Could not find sccache.exe under: $destRoot"
          Get-ChildItem -Path $destRoot -Recurse | Select-Object FullName | Format-Table -AutoSize
          throw "sccache.exe not found after extracting archive"
        }

        # Copy into a short, stable dir to avoid Windows long-path issues
        $binDir = "$env:RUNNER_TEMP\bin\sccache"
        if (Test-Path $binDir) { Remove-Item $binDir -Recurse -Force }
        New-Item -ItemType Directory -Path $binDir | Out-Null

        $binExe = Join-Path $binDir 'sccache.exe'
        Copy-Item -LiteralPath $sccacheExe.FullName -Destination $binExe -Force

        $binDir | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

        # Verify in the same step using absolute path (so we don't depend on PATH update timing)
        & $binExe --version

    - name: "Configure sccache env (S3 backend)"
      shell: powershell
      env:
        S3_BUCKET: ${{ inputs.s3-bucket }}
        S3_HOST: ${{ inputs.s3-host }}
        S3_ACCESS_KEY: ${{ inputs.s3-access-key }}
        S3_SECRET_KEY: ${{ inputs.s3-secret-key }}
      run: |
        Add-Content -Path $env:GITHUB_ENV -Value "RUSTC_WRAPPER=sccache"
        Add-Content -Path $env:GITHUB_ENV -Value "CARGO_INCREMENTAL=0"

        # S3 backend 
        if ($env:S3_BUCKET) { Add-Content -Path $env:GITHUB_ENV -Value "SCCACHE_BUCKET=$env:S3_BUCKET" }
        if ($env:S3_HOST) { Add-Content -Path $env:GITHUB_ENV -Value "SCCACHE_ENDPOINT=$env:S3_HOST" }
        if ($env:S3_ACCESS_KEY) { Add-Content -Path $env:GITHUB_ENV -Value "AWS_ACCESS_KEY_ID=$env:S3_ACCESS_KEY" }
        if ($env:S3_SECRET_KEY) { Add-Content -Path $env:GITHUB_ENV -Value "AWS_SECRET_ACCESS_KEY=$env:S3_SECRET_KEY" }

        Add-Content -Path $env:GITHUB_ENV -Value "SCCACHE_REGION=auto"
        Add-Content -Path $env:GITHUB_ENV -Value "SCCACHE_S3_USE_SSL=true"
        Add-Content -Path $env:GITHUB_ENV -Value "SCCACHE_S3_ENABLE_VIRTUAL_HOST_STYLE=false"

    - name: "Guard: disable sccache when env is misconfigured"
      shell: powershell
      env:
        S3_BUCKET: ${{ inputs.s3-bucket }}
        S3_HOST: ${{ inputs.s3-host }}
        S3_ACCESS_KEY: ${{ inputs.s3-access-key }}
        S3_SECRET_KEY: ${{ inputs.s3-secret-key }}
      run: |
        $ErrorActionPreference = 'Continue'

        # If any required env vars are missing, don't enable sccache.
        if (-not $env:S3_BUCKET -or -not $env:S3_HOST -or -not $env:S3_ACCESS_KEY -or -not $env:S3_SECRET_KEY) {
          Write-Host 'sccache disabled: missing one or more S3 environment variables'
          Add-Content -Path $env:GITHUB_ENV -Value 'RUSTC_WRAPPER='
        }
