name: "Setup sccache"
description: "Installs sccache for caching Rust builds"
inputs:
  version:
    description: "Sccache version"
    required: false
    default: "0.12.0"
runs:
  using: "composite"
  steps:
    - name: "Check for existing sccache"
      id: check
      shell: powershell
      run: |
        if (Get-Command sccache -ErrorAction SilentlyContinue) {
          Write-Host "sccache already installed"
          "installed=true" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
        } else {
          "installed=false" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
        }

    - name: "Install sccache"
      if: steps.check.outputs.installed != 'true'
      env:
        SCCACHE_VERSION: ${{ inputs.version }}
      shell: powershell
      run: |
        $ErrorActionPreference = "Stop"

        $v = $env:SCCACHE_VERSION
        $url = "https://github.com/mozilla/sccache/releases/download/v$v/sccache-v$v-x86_64-pc-windows-msvc.zip"
        $zip = "$env:RUNNER_TEMP\sccache-$v.zip"
        $destRoot = "$env:RUNNER_TEMP\sccache"

        if (Test-Path $destRoot) { Remove-Item $destRoot -Recurse -Force }
        New-Item -ItemType Directory -Path $destRoot | Out-Null

        Invoke-WebRequest $url -OutFile $zip
        Expand-Archive -LiteralPath $zip -DestinationPath $destRoot -Force

        # Find the directory that actually contains sccache.exe (zip layouts can vary)
        $sccacheExe = Get-ChildItem -Path $destRoot -Recurse -Filter "sccache.exe" | Select-Object -First 1
        if (-not $sccacheExe) {
          Write-Host "Could not find sccache.exe under: $destRoot"
          Write-Host "Directory listing:" 
          Get-ChildItem -Path $destRoot -Recurse | Select-Object FullName | Format-Table -AutoSize
          throw "sccache.exe not found after extracting archive"
        }

        $exeDir = Split-Path -Parent $sccacheExe.FullName
        Write-Host "Adding to PATH: $exeDir"
        $exeDir | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

        # Fails pipeline if command unsuccessful
        sccache --version

    - name: "Enable sccache + GitHub Actions cache backend"
      shell: powershell
      run: |
        # Rust: use sccache as compiler wrapper
        Add-Content -Path $env:GITHUB_ENV -Value "RUSTC_WRAPPER=sccache"

        # Optional but commonly recommended for CI: incremental builds aren't cacheable by sccache
        Add-Content -Path $env:GITHUB_ENV -Value "CARGO_INCREMENTAL=0"

        # Enable GitHub Actions cache backend for sccache
        Add-Content -Path $env:GITHUB_ENV -Value "SCCACHE_GHA_ENABLED=true"

        # Optional: keep cache size bounded (local server metadata; actual storage is in GHA cache backend)
        Add-Content -Path $env:GITHUB_ENV -Value "SCCACHE_CACHE_SIZE=5G"

    - name: "Export required runtime variables for sccache (GHA backend)"
      if: ${{ runner.os == 'Windows' }}
      uses: actions/github-script@v7
      with:
        script: |
          core.exportVariable('ACTIONS_RESULTS_URL', process.env.ACTIONS_RESULTS_URL || '');
          core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

    - name: "Start sccache server + show initial stats"
      shell: powershell
      run: |
        $ErrorActionPreference = "Stop"
        if (-not (Get-Command sccache -ErrorAction SilentlyContinue)) {
          Write-Host "sccache is not on PATH at start step. PATH is:"
          Write-Host $env:PATH
          throw "sccache not found on PATH"
        }
        sccache --start-server
        sccache --show-stats
