name: Build Tauri App JONAS KRUCKENBERG VERSION

on:
  push:
    tags:
      - test-kruck*

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-binaries:
    strategy:
      fail-fast: false
      matrix:
        platform: [self-hosted, ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      PAPI_PATH: "placeholder"
      OIDC_BASE_URL: "placeholder"
      OIDC_CLIENT_ID: "placeholder"
      OIDC_CLIENT_SECRET: "placeholder"
      RUST_BACKTRACE: full
      RUST_LOG: debug
    steps:
      - uses: actions/checkout@v2

      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'self-hosted' || matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf

      - name: install Rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy

      - name: Run rustfmt
        working-directory: ./src-tauri
        run: cargo fmt --all -- --check

      - name: Run clippy
        working-directory: ./src-tauri
        run: cargo clippy --all -- -D warnings

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      - name: Sync node version and setup cache
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm' # Set this to npm, yarn or pnpm.

      - name: Install frontend dependencies
        run: npm ci

      - name: Lint frontend
        run: npm run lint

      - uses: JonasKruckenberg/tauri-build@v1
        id: tauri_build