on: pull_request

name: Npm code check

jobs:
  code-check-npm:
    runs-on: [ self-hosted, Linux ]
    steps:
      - uses: actions/checkout@v4
      - name: Sync node version and setup cache
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm' # Set this to npm, yarn or pnpm.
      - name: Install frontend dependencies
        run: npm ci
      - name: Run EsLint
        if: always()
        run: npm run lint
      - name: Run frontend tests
        if: always()
        run: npm run test
