on: pull_request

name: Npm code check

jobs:
  format:
    runs-on: [ self-hosted, Linux ]
    steps:
      - uses: actions/checkout@v4
      - name: Install modules
        run: npm install
      - name: Run EsLint
        if: always()
        run: npm run lint
      - name: Run frontend tests
        if: always()
        run: npm run test
